# "org" ensures this Service is used with the correct Serverless Framework Access Key.
# org: jsd23
# "service" is the name of this project. This will also be added to your AWS resource names.
service: meetupBE

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:${aws:region}:*:table/*

functions:
  signup:
    handler: getRooms/index.handler
    events:
      - httpApi:
          path: /signup
          method: post

  login:
    handler: addRoom/index.handler
    events:
      - httpApi:
          path: /login
          method: post

  getMeetups:
    handler: deleteBooking/index.handler
    events:
      - httpApi:
          path: /meetups
          method: get

  getOneMeetup:
    handler: newBooking/index.handler
    events:
      - httpApi:
          path: /meetups/{meetupId}
          method: get

  registerToMeetup:
    handler: newBooking/index.handler
    events:
      - httpApi:
          path: /meetups
          method: post

  updateRegistration:
    handler: newBooking/index.handler
    events:
      - httpApi:
          path: /meetups
          method: put

  removeRegistration:
    handler: newBooking/index.handler
    events:
      - httpApi:
          path: /meetups
          method: delete

  postReview:
    handler: newBooking/index.handler
    events:
      - httpApi:
          path: /reviews
          method: post

  getReviews:
    handler: getBookings/index.handler
    events:
      - httpApi:
          path: /reviews
          method: get

resources:
  Resources:
    meetupUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: meetupUsersTable
        AttributeDefinitions:
          - AttributeName: mail
            AttributeType: S
          # - AttributeName:
          #   AttributeType: S
        KeySchema:
          - AttributeName: mail
            KeyType: HASH
          # - AttributeName:
          #   KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST

    meetupReviewsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookings
        AttributeDefinitions:
          - AttributeName: meetupId
            AttributeType: S
          # - AttributeName:
          #   AttributeType: S
        KeySchema:
          - AttributeName: meetupId
            KeyType: HASH
          # - AttributeName:
          #   KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST

    meetupTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: meetupTable
        AttributeDefinitions:
          - AttributeName: meetupId
            AttributeType: S
          # - AttributeName:
          #   AttributeType: S
        KeySchema:
          - AttributeName: meetupId
            KeyType: HASH
          # - AttributeName:
          #   KeyType: "RANGE"
        # GlobalSecondaryIndexes:
        #   - IndexName: meetupParticipantsIndex
        #     KeySchema:
        #       - AttributeName: meetupId
        #         KeyType: HASH
        #       - AttributeName:
        #         KeyType: RANGE
        #     Projection:
        #       ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
