name: Deploy dev meetup

on:
  push:
    branches:
      - dev
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }} #dev/test bucket istället
  AWS_REGION: "eu-north-1"
  SOURCE_DIR: "client/dist"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: cd client && npm install
      - name: Build dist
        run: cd client && npm run build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
